FROM php:7.4-fpm-alpine

# Install gd, iconv, mbstring, mysql, soap, sockets, zip, and zlib extensions
# see example at https://hub.docker.com/_/php/
RUN apk add --update \
        $PHPIZE_DEPS \
        freetype-dev \
        git \
        libjpeg-turbo-dev \
        libpng-dev \
        libxml2-dev \
        libzip-dev \
        openssh-client \
        php7-json \
        php7-openssl \
        php7-pdo \
        php7-pdo_mysql \
        php7-session \
        php7-simplexml \
        php7-tokenizer \
        php7-xml \
        imagemagick \
        imagemagick-libs \
        imagemagick-dev \
        php7-imagick \
        php7-pcntl \
        php7-zip \
        sqlite \
    && docker-php-ext-install iconv soap sockets exif bcmath pdo_mysql mysqli \
    && docker-php-ext-configure gd --with-jpeg --with-freetype \
    && docker-php-ext-install gd \
    && docker-php-ext-install zip


# Install xdebug
RUN pecl install xdebug \
 && docker-php-ext-enable xdebug

# Enable XDebug
ADD xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini

WORKDIR /var/www/html/